// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzhnsTzBSD59ohJfJ73wTq_2EwNk38Wcg',
    appId: '1:602022557688:web:8ac4f52625d1314079080d',
    messagingSenderId: '602022557688',
    projectId: 'hostel-finder-b9a3f',
    authDomain: 'hostel-finder-b9a3f.firebaseapp.com',
    storageBucket: 'hostel-finder-b9a3f.appspot.com',
    measurementId: 'G-ZJ5QHT7SDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIXXclhTV5OUzHuQyWrQG-SPMhTdWneMw',
    appId: '1:602022557688:android:97cf3702dc2b020879080d',
    messagingSenderId: '602022557688',
    projectId: 'hostel-finder-b9a3f',
    storageBucket: 'hostel-finder-b9a3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE54sOQoxPrQjBYGh_eKcG3niWSFJTWeQ',
    appId: '1:602022557688:ios:375b6e0a22feeedf79080d',
    messagingSenderId: '602022557688',
    projectId: 'hostel-finder-b9a3f',
    storageBucket: 'hostel-finder-b9a3f.appspot.com',
    iosBundleId: 'com.example.hostelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE54sOQoxPrQjBYGh_eKcG3niWSFJTWeQ',
    appId: '1:602022557688:ios:7b37f81ccf10532d79080d',
    messagingSenderId: '602022557688',
    projectId: 'hostel-finder-b9a3f',
    storageBucket: 'hostel-finder-b9a3f.appspot.com',
    iosBundleId: 'com.example.hostelApp.RunnerTests',
  );
}
